version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      # - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    ports:
      - '8000:80'
    depends_on:
      - db
  db:
    image: mysql:8.0-debian    
    restart: always
    environment:
      - MYSQL_DATABASE=organizacao_defesa
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    cap_add:
      - SYS_NICE