version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:      
      - ./:/app
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      - BASE_URL=https://sistema-de-defesas-api.app.ic.ufba.br
      - BASE_FRONTEND_URL=https://sistema-de-defesas.app.ic.ufba.br
      - MAIL_PASSWORD=
  db:
    image: mysql:5.7-debian    
    restart: always
    environment:
      - MYSQL_DATABASE=organizacao_defesa
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3309:3306'
    cap_add:
      - SYS_NICE