version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:      
      - ./:/app
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      - BASE_URL=http://localhost:80
  db:
    image: mysql:5.7-debian    
    restart: always
    environment:
      - MYSQL_DATABASE=organizacao_defesa
      - MYSQL_ROOT_PASSWORD=root
    cap_add:
      - SYS_NICE